kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: pwYwFaYXXmj51OK++oHldv0m/llrQ0LekX/r4VuUir4=
      - identity: {}
